# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Habit < Formula
  desc "A cli application for tracking daily habits."
  homepage "https://github.com/qba73/habit"
  version "0.1.8"

  on_macos do
    url "https://github.com/qba73/habit/releases/download/v0.1.8/habit_0.1.8_darwin_all.tar.gz"
    sha256 "d22b1723356d63b0cbcf1bb57f8a491226e4ad3d1acbcfeca66626ac891cf1d0"

    def install
      bin.install "habctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qba73/habit/releases/download/v0.1.8/habit_0.1.8_linux_arm64.tar.gz"
      sha256 "fb6ac1c0f2195221cdb3fe6453085969dee803d3e7ea6096b1a2ef2e8f7571c9"

      def install
        bin.install "habctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qba73/habit/releases/download/v0.1.8/habit_0.1.8_linux_amd64.tar.gz"
      sha256 "58a85d87a2cab9c0f267e04cc23fcf7f755ccd2b86ea8ff6dd8815e4ec3d536f"

      def install
        bin.install "habctl"
      end
    end
  end
end
