# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipr < Formula
  desc ""
  homepage "https://github.com/qba73/ipr"
  version "0.0.3"

  on_macos do
    url "https://github.com/qba73/ipr/releases/download/v0.0.3/ipr_0.0.3_darwin_all.tar.gz"
    sha256 "1b1683912ef4fd1eb678b0185ac07802f193408467f1b0e8beb5f5ed0f3b8176"

    def install
      bin.install "ipr"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qba73/ipr/releases/download/v0.0.3/ipr_0.0.3_linux_arm64.tar.gz"
      sha256 "8fde908791bfc841f73627ce355ac23f3843075e243d22a20440c3bb6e2c2b99"

      def install
        bin.install "ipr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qba73/ipr/releases/download/v0.0.3/ipr_0.0.3_linux_amd64.tar.gz"
      sha256 "2f29979bdef312af4df03ef5d7a9a704d30c454123f0b571fef3ac9c11fc8a30"

      def install
        bin.install "ipr"
      end
    end
  end
end
