# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morningpost < Formula
  desc "A cli utility for generating a morning newspaper."
  homepage "https://github.com/qba73/morningpost"
  version "0.0.1"

  on_macos do
    url "https://github.com/qba73/morningpost/releases/download/v0.0.1/morningpost_0.0.1_darwin_all.tar.gz"
    sha256 "c360412c0294884748018fcf3c71aadf2c924ea02c01547c335af6c012ad4c4d"

    def install
      bin.install "morningpost"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qba73/morningpost/releases/download/v0.0.1/morningpost_0.0.1_linux_arm64.tar.gz"
      sha256 "44a15b0361ffaf991fab6e0ed21848f484f77e245f38973501376ef702f5729d"

      def install
        bin.install "morningpost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qba73/morningpost/releases/download/v0.0.1/morningpost_0.0.1_linux_amd64.tar.gz"
      sha256 "a8bcaaa7114ec6edf374d540db88345d5a9fb469402afee2540f1e4eb0c3503c"

      def install
        bin.install "morningpost"
      end
    end
  end
end
